import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, collection, addDoc, updateDoc, doc, query, where, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id);let currentUser=null;
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[s]));}
function formData(){const f=$("ispForm"),data={};for(const el of f.elements){if(!el.name||el.type==='submit'||el.type==='button')continue;if(el.type==='checkbox'){if(!data[el.name])data[el.name]=[];if(el.checked)data[el.name].push(el.value);}else if(el.type==='radio'){if(el.checked)data[el.name]=el.value;else if(!(el.name in data))data[el.name]='';}else data[el.name]=el.value;}return data;}
function clearForm(){$("ispForm").reset();$("docId").value='';}
function fillForm(data){clearForm();$("docId").value=data.id||'';for(const el of $("ispForm").elements){if(!el.name)continue;const v=data.form?.[el.name];if(el.type==='checkbox')el.checked=Array.isArray(v)&&v.includes(el.value);else if(el.type==='radio')el.checked=v===el.value;else if(v!==undefined)el.value=v??'';}}
$("loginBtn").onclick=()=>signInWithPopup(auth,provider);$("logoutBtn").onclick=()=>signOut(auth);$("newIspBtn").onclick=()=>{clearForm();showPage('ispEditor')};$("backBtn").onclick=()=>showPage('home');
document.querySelectorAll('.nav[data-view]').forEach(btn=>btn.onclick=async()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));btn.classList.add('active');showPage(btn.dataset.view);if(btn.dataset.view==='mine')await loadDocs();});
$("ispForm").onsubmit=async e=>{e.preventDefault();if(!currentUser)return;const form=formData();const payload={ownerUid:currentUser.uid,ownerEmail:currentUser.email||'',type:'ISP',studentName:(form.studentName||'').trim(),studentId:(form.studentId||'').trim(),form,updatedAt:serverTimestamp()};const id=$("docId").value;if(id)await updateDoc(doc(db,'adminDocuments',id),payload);else{payload.createdAt=serverTimestamp();const ref=await addDoc(collection(db,'adminDocuments'),payload);$("docId").value=ref.id;}alert('草稿已儲存');};
async function loadDocs(){if(!currentUser)return;const q=query(collection(db,'adminDocuments'),where('ownerUid','==',currentUser.uid));const snap=await getDocs(q),items=[];snap.forEach(s=>items.push({id:s.id,...s.data()}));items.sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));const list=$("docList");list.innerHTML='';if(!items.length){list.innerHTML='<div class="doc-item">目前尚無行政文書。</div>';return;}for(const d of items){const div=document.createElement('div');div.className='doc-item';div.innerHTML=`<div><strong>${esc(d.studentName||'未命名')}｜ISP</strong><div class="doc-meta">${esc(d.studentId||'尚未填學號')}　第一階段資料</div></div><button class="secondary">開啟</button>`;div.querySelector('button').onclick=()=>{fillForm(d);showPage('ispEditor')};list.appendChild(div);}}
onAuthStateChanged(auth,user=>{currentUser=user;if(user){$("loginView").classList.add('hidden');$("appView").classList.remove('hidden');$("userEmail").textContent=user.email||'';}else{$("appView").classList.add('hidden');$("loginView").classList.remove('hidden');}});
